@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.realyusufismail.bentenmod.client.renderer;

import javax.annotation.ParametersAreNonnullByDefault;
import mcp.MethodsReturnNonnullByDefault;
