@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.realyusufismail.bentenmod.modules.bententable.recipes;

import javax.annotation.ParametersAreNonnullByDefault;
import mcp.MethodsReturnNonnullByDefault;
