@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.realyusufismail.bentenmod.client;

import javax.annotation.ParametersAreNonnullByDefault;
import mcp.MethodsReturnNonnullByDefault;
