@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.realyusufismail.bentenmod.core.itemgroup;

import javax.annotation.ParametersAreNonnullByDefault;
import mcp.MethodsReturnNonnullByDefault;
