@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.realyusufismail.bentenmod.entity;

import javax.annotation.ParametersAreNonnullByDefault;
import mcp.MethodsReturnNonnullByDefault;
