name: Release JAR

on:
  push:
    tags:
      - 'v*'

defaults:
  run:
    shell: bash

env:
  JAVA_VERSION: 17

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'adopt'
      - uses: actions/checkout@v3
      - name: Build shadow jar
        run: ./gradlew shadowJar
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          files: build/libs/ben_10_mod.jar